classDiagram
    ChessGame o-- Player
    ChessGame *-- Board
    ChessGame *-- GameStatus
    ChessGame ..> GameResult
    ChessGame --o Move
    Player *-- Color
    Player *-- PlayerType
    Player <|-- HumanPlayer
    Player <|-- AIPlayer
    Player --|> IPlayer
    Move -- Position
    Move *-- MoveType
    Square --|> ISquare
    Board --|> IBoard
    Board --o Square
    Board o-- Piece
    Piece --|> IPiece
    Color --* Piece
    Piece *-- PieceType
    Piece <|-- King
    Piece <|-- Queen
    Piece <|-- Rook
    Piece <|-- Bishop
    Piece <|-- Knight
    Piece <|-- Pawn
    class ChessGame {
      -int _moveCount
      -List~.Move~ _moveHistory
      -GameStatus _gameStatus
      -IPlayer _currentPlayer
      -List~.IPlayer~ _players
      -IBoard _board
      +Action<.GameResult>? OnGameEnded
      +Action<.IPlayer>? OnCheckDetected
      +ChessGame(Board board)
      +StartGame() void
      +EndGame(GameResult result) void
      +MakeMove(Move move) void
      +UndoLastMove() void
      -GetAllValidMoves(Player player, Board board) List~.Move~
      -GetPiece(Position pos) Piece
      -SetPiece(Position pos, Piece piece) void
      -RemovePiece(Position pos) Piece
      -IsCheck(Player player, Board board) boolean
      -IsCheckMate(Player player, Board board) boolean
      -IsStaleMate(Player player, Board board) boolean
      -IsCastle(Move move, Board board) boolean
      -IsValidMove(Move move, Board board) boolean
    }
    class Player {
      +string Name
      +PlayerType type
      +Color Color
      +List~.IPiece~ Pieces
      +Player(string name, PlayerType type, Color color)
      +OfferDraw() void
    }
    class HumanPlayer {
      -int _wins
      +SelectPiece(Position pos) Piece
      +ConfirmMove() boolean
    }
    class AIPlayer {
      -int _thinkingTime
      +ExecuteRandomMove() Move
      +EvaluatePosition() int
    }
    class Board {
      +List~.ISquare~ Squares
      +List~.IPiece~ CapturedPieces
      +List~.IPiece~ GetAllPieces
      +Board()
      +GenerateBoard() void
    }
    class Square {
      +Piece piece
      +Position position
    }
    class Piece {
      +PieceType Type
      +Color Color
      +Position Position
      +boolean HasMoved
      +Piece(Color color, PieceType pieceType, Position position)
      +GetValidMoves(Board board) List~.Move~
      +Move(Position newPosition) void
      -CanMoveTo(Position pos, Board board) boolean
    }
    class King {
      -boolean _inCheck
      +King(Color color, Position position)
      +GetValidMoves(Board board) List~.Move~
      -CanCastle(Board board, boolean kingSide) boolean
      -IsInCheck(Board board) boolean
    }
    class Queen {
      +Queen(Color color, Position position)
      +GetValidMoves(Board board) List~.Move~
      -CanMoveDiagonal(Position pos, Board board) boolean
      -CanMoveHorizontal(Position pos, Board board) boolean
      -CanMoveVertical(Position pos, Board board) boolean
    }
    class Rook {
      +Rook(Color color, Position position)
      +GetValidMoves(Board board) List~.Move~
      -CanMoveHorizontal(Position pos, Board board) boolean
      -CanMoveVertical(Position pos, Board board) boolean
    }
    class Bishop {
      +Bishop(Color color, Position position)
      +GetValidMoves(Board board) List~.Move~
      -CanMoveDiagonal(Position pos, Board board) boolean
    }
    class Knight {
      +Knight(Color color, Position position)
      +GetValidMoves(Board board) List~.Move~
      -CanMoveLShape(Position pos, Board board) boolean
    }
    class Pawn {
      -boolean _isFirstMove
      +Pawn(Color color, Position position)
      +GetValidMoves(Board board) List~.Move~
      -CanMoveForward(Position pos, Board board) boolean
      -CanCapture(Position pos, Board board) boolean
      -CanEnPassant(Board board) boolean
      -CanPromote() boolean
      +PromoteTo(PieceType) void
    }
    class Position {
      <<struct>>
      -int x
      -int y
      +Position(int x, int y)
      +IsValid() boolean
      +ToString() string
    }
    class Move {
      -Position _startPosition
      -Position _targetPosition
      -Piece _pieceType
      -Piece _capturedPiece
      -MoveType _moveType
      +IsValid(Board board) boolean
      +ToString() string
    }
    class IPlayer {
      <<interface>>
      +string Name
      +PlayerType Type
      +Color Color
      +List~.IPiece~ Pieces
    }
    class ISquare {
      <<interface>>
      +Piece piece
      +Position position
    }
    class IPiece {
      <<interface>>
      +PieceType Type
      +Color Color
      +Position Position
      +boolean HasMoved
      +GetValidMoves(Board board) List~Move~
      +Move(Position position) void
    }
    class IBoard {
      <<interface>>
      +List~.ISquare~ Squares
      +List~.IPiece~ CapturedPieces
      +List~.IPiece~ GetAllPieces
      +GenerateBoard() void
    }
    class Color {
      <<enumeration>>
      WHITE
      BLACK
    }
    class GameStatus {
      <<enumeration>>
      NOT_STARTED
      IN_PROGRESS
      CHECKMATE
      STALEMATE
      DRAW
      RESIGNED
    }
    class GameResult {
      <<enumeration>>
      WHITE_WIN
      BLACK_WIN
      DRAW
      LOSE
    }
    class PlayerType {
      <<enumeration>>
      HUMAN
      AI
    }
    class MoveType {
      <<enumeration>>
      NORMAL
      CAPTURE
      CASTLE_KINGSIDE
      CASTLE_QUEENSIDE
      EN_PASSANT
      PROMOTION
    }
    class PieceType {
      <<enumeration>>
      KING
      QUEEN
      Rook
      BISHOP
      KNIGHT
      PAWN
    }
